
import __ASTRO_IMAGE_IMPORT_Z1tx7dX from "/src/assets/hero/hero1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Fhero.md";
import __ASTRO_IMAGE_IMPORT_1C0jtC from "/src/assets/hero/hero2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Fhero.md";
import __ASTRO_IMAGE_IMPORT_Z2dXlcL from "/src/assets/tours/popular/popular1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z2d6DAU from "/src/assets/tours/popular/popular2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_1qJYrK from "/src/assets/tours/popular/popular3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_ZMq2jM from "/src/assets/tours/amsterdam/amsterdam1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z2dKx53 from "/src/assets/tours/amsterdam/amsterdam2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_cuiGI from "/src/assets/tours/amsterdam/amsterdam3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_ZeoLD from "/src/assets/tours/amsterdam/amsterdam4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z1qyTwT from "/src/assets/tours/amsterdam/amsterdam5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z2dmgU0 from "/src/assets/tours/boat/boat1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_1qum8F from "/src/assets/tours/boat/boat2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_2uaLnB from "/src/assets/tours/other/other1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_13PgCl from "/src/assets/tours/other/other2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_rdFne from "/src/assets/tours/other/other3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z1MOISb from "/src/assets/tours/other/other4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_1Q1Tau from "/src/assets/tours/other/other5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_pGope from "/src/assets/tours/other/other6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
import __ASTRO_IMAGE_IMPORT_Z10D6l2 from "/src/assets/tours/other/other7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md";
export default new Map([["/src/assets/hero/hero1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Fhero.md", __ASTRO_IMAGE_IMPORT_Z1tx7dX], ["/src/assets/hero/hero2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhero%2Fhero.md", __ASTRO_IMAGE_IMPORT_1C0jtC], ["/src/assets/tours/popular/popular1.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z2dXlcL], ["/src/assets/tours/popular/popular2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z2d6DAU], ["/src/assets/tours/popular/popular3.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_1qJYrK], ["/src/assets/tours/amsterdam/amsterdam1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_ZMq2jM], ["/src/assets/tours/amsterdam/amsterdam2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z2dKx53], ["/src/assets/tours/amsterdam/amsterdam3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_cuiGI], ["/src/assets/tours/amsterdam/amsterdam4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_ZeoLD], ["/src/assets/tours/amsterdam/amsterdam5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z1qyTwT], ["/src/assets/tours/boat/boat1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z2dmgU0], ["/src/assets/tours/boat/boat2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_1qum8F], ["/src/assets/tours/other/other1.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_2uaLnB], ["/src/assets/tours/other/other2.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_13PgCl], ["/src/assets/tours/other/other3.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_rdFne], ["/src/assets/tours/other/other4.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z1MOISb], ["/src/assets/tours/other/other5.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_1Q1Tau], ["/src/assets/tours/other/other6.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_pGope], ["/src/assets/tours/other/other7.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Ftour-categories%2Fcategories.md", __ASTRO_IMAGE_IMPORT_Z10D6l2]]);
		