[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  # Use one at a time:
  Cache-Control = "public, max-age=0, must-revalidate"
  Content-Security-Policy = "default-src 'self' data: blob: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: blob: https:; connect-src 'self' https:; font-src 'self' data: https:; frame-src 'self' https:;"

[[headers]]
for = "/sitemap*.xml"
  [headers.values]
  Content-Type = "application/xml; charset=UTF-8"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions-serve"
 
[functions]
  node_bundler = "esbuild"

[[headers]]
for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/_astro/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/fonts/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/favicon2.ico"
  [headers.values]
  Cache-Control = "public, max-age=2592000"

[[headers]]
for = "/*.webp"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.avif"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/ru"
  to   = "/"
  status = 301
  force = true

[[redirects]]
  from = "/ru/*"
  to   = "/:splat"
  status = 301
  force = true