[[headers]]
for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  Referrer-Policy = "strict-origin-when-cross-origin"
  # Use one at a time:
  # Content-Security-Policy-Report-Only = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; object-src 'none'; connect-src 'self'; font-src 'self'; img-src 'self' data:; script-src 'self'; style-src 'self'; upgrade-insecure-requests"
  Content-Security-Policy = "default-src 'self'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; object-src 'none'; connect-src 'self' https://www.google-analytics.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://www.google-analytics.com; script-src 'self' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; upgrade-insecure-requests"

[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions-serve"
 
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/oauth"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/callback"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/token"
  to   = "/.netlify/functions/oauth"
  status = 200
