[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions-serve"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/oauth"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/callback"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/token"
  to   = "/.netlify/functions/oauth"
  status = 200

# Cache headers for static assets
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.avif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"