[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Map all three public paths to ONE function
[[redirects]]
  from = "/oauth"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/callback"
  to   = "/.netlify/functions/oauth"
  status = 200

[[redirects]]
  from = "/token"
  to   = "/.netlify/functions/oauth"
  status = 200
