media_folder: "public/assets" # Location where files will be stored
public_folder: "/assets" # The src attribute for uploaded media

publish_mode: simple

collections:
  - name: "hero"
    label: "Hero Section"
    files:
      - label: "Hero Content"
        name: "hero"
        file: "src/content/hero/hero.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - label: "Hero Images"
            name: "images"
            widget: "object"
            fields:
              - { label: "Main Image", name: "mainImage", widget: "image" }
              - {
                  label: "Main Image Alt Text",
                  name: "mainImageAlt",
                  widget: "string",
                }
              - {
                  label: "Secondary Image",
                  name: "secondaryImage",
                  widget: "image",
                }
              - {
                  label: "Secondary Image Alt Text",
                  name: "secondaryImageAlt",
                  widget: "string",
                }

  - name: "tour-categories"
    label: "Tour Categories"
    files:
      - label: "Tour Filter Categories"
        name: "tour-categories"
        file: "src/content/tour-categories/categories.md"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - { label: "Category ID", name: "id", widget: "string" }
              - { label: "Category Title", name: "title", widget: "string" }
              - label: "Tours"
                name: "tours"
                widget: "list"
                fields:
                  - { label: "Tour Title", name: "title", widget: "string" }
                  - { label: "Price", name: "price", widget: "string" }
                  - { label: "Duration", name: "duration", widget: "string" }
                  - { label: "Tour Image", name: "image", widget: "image" }
                  - { label: "Image Alt Text", name: "alt", widget: "string" }
                  - {
                      label: "Tour Slug",
                      name: "slug",
                      widget: "string",
                      hint: "URL-friendly identifier (e.g., labuan-bajo-adventure)",
                    }

  - name: "testimonials"
    label: "Testimonials"
    files:
      - label: "Customer Testimonials"
        name: "testimonials"
        file: "src/content/testimonials/testimonials.md"
        fields:
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - label: "Author"
                name: "author"
                widget: "object"
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Title", name: "title", widget: "string" }
                  - { label: "Company", name: "company", widget: "string" }
                  - { label: "Avatar Image", name: "avatar", widget: "image" }
              - {
                  label: "Rating",
                  name: "rating",
                  widget: "number",
                  min: 1,
                  max: 5,
                  default: 5,
                }
              - {
                  label: "Featured",
                  name: "featured",
                  widget: "boolean",
                  default: false,
                }

  - name: "tours"
    label: "Tours"
    folder: "src/content/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Detailed Description", name: "body", widget: "markdown" }
      - { label: "Price (USD)", name: "price", widget: "number" }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "Group Size", name: "groupSize", widget: "string" }
      - {
          label: "Rating",
          name: "rating",
          widget: "number",
          min: 1,
          max: 5,
          step: 0.1,
        }
      - { label: "Review Count", name: "reviewCount", widget: "number" }
      - { label: "Main Image", name: "mainImage", widget: "image" }
      - {
          label: "Gallery Images",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Location", name: "location", widget: "string" }
      - {
          label: "Country",
          name: "country",
          widget: "string",
          default: "Indonesia",
        }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        field: { label: "Highlight", name: "highlight", widget: "string" }
      - label: "Itinerary"
        name: "itinerary"
        widget: "list"
        fields:
          - { label: "Day", name: "day", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - label: "Activities"
            name: "activities"
            widget: "list"
            field: { label: "Activity", name: "activity", widget: "string" }
      - label: "Included"
        name: "included"
        widget: "list"
        field: { label: "Item", name: "item", widget: "string" }
      - label: "Not Included"
        name: "notIncluded"
        widget: "list"
        field: { label: "Item", name: "item", widget: "string" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Profile Image", name: "profileImage", widget: "image" }

backend:
  name: git-gateway
  repo: anisa07/jasmine-tours
  branch: master
