media_folder: "public/assets" # Location where files will be stored
public_folder: "/assets" # The src attribute for uploaded media

collections:
  - name: "tours"
    label: "Tours"
    folder: "src/content/tours"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Detailed Description", name: "body", widget: "markdown" }
      - { label: "Price (USD)", name: "price", widget: "number" }
      - { label: "Duration", name: "duration", widget: "string" }
      - { label: "Group Size", name: "groupSize", widget: "string" }
      - {
          label: "Rating",
          name: "rating",
          widget: "number",
          min: 1,
          max: 5,
          step: 0.1,
        }
      - { label: "Review Count", name: "reviewCount", widget: "number" }
      - { label: "Main Image", name: "mainImage", widget: "image" }
      - {
          label: "Gallery Images",
          name: "gallery",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" },
        }
      - { label: "Location", name: "location", widget: "string" }
      - {
          label: "Country",
          name: "country",
          widget: "string",
          default: "Indonesia",
        }
      - label: "Highlights"
        name: "highlights"
        widget: "list"
        field: { label: "Highlight", name: "highlight", widget: "string" }
      - label: "Itinerary"
        name: "itinerary"
        widget: "list"
        fields:
          - { label: "Day", name: "day", widget: "number" }
          - { label: "Title", name: "title", widget: "string" }
          - label: "Activities"
            name: "activities"
            widget: "list"
            field: { label: "Activity", name: "activity", widget: "string" }
      - label: "Included"
        name: "included"
        widget: "list"
        field: { label: "Item", name: "item", widget: "string" }
      - label: "Not Included"
        name: "notIncluded"
        widget: "list"
        field: { label: "Item", name: "item", widget: "string" }
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: true,
        }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Profile Image", name: "profileImage", widget: "image" }

backend:
  name: github
  repo: anisa07/mvp-netlify-cms
  branch: version-3
  base_url: https://superlative-kitten-1f442a.netlify.app
  auth_endpoint: /oauth
